language: c
services: docker
install: docker build -t opam-repo-dev .
script: docker run --rm -it opam-repo-dev bash /opam-repo-dev/test/install-package.sh $PKG
env:
  - PKG=libvirt.djs55#typo
  - PKG=localstorage-js.djs55#opam
  - PKG=logminer.jeromemaloberti#master
  - PKG=message-switch.jonludlam#ppx
  - PKG=mirage-block-volume.mirage#master
  - PKG=mtime.patched-0.8.1+no-js
  - PKG=nbd.xapi-project#master
  - PKG=rrddump.xapi-project#master
  - PKG=shared-block-ring.2.2.0
  - PKG=shared-block-ring.mirage#master
  - PKG=vncproxy.xapi-project#master
  - PKG=vxs.xapi-project#master
  - PKG=xapi-backtrace.mseri#ppx
  - PKG=xapi-forkexecd.xapi-project#master
  - PKG=xapi-idl.jonludlam#ppx
  - PKG=xapi-inventory.xapi-project#master
  - PKG=xapi-libs-transitional.xapi-project#master
  - PKG=xapi-netdev.xapi-project#master
  - PKG=xapi-plugin.xapi-project#master
  - PKG=xapi-rrdd-plugin.xapi-project#master
  - PKG=xapi-rrdd.xapi-project#master
  - PKG=xapi-rrd-transport.xapi-project#master
  - PKG=xapi-rrd.xapi-project#master
  - PKG=xapi-squeezed.xapi-project#master
  - PKG=xapi-stdext.xapi-project#master
  - PKG=xapi-storage-cli.0.9.7
  - PKG=xapi-storage-ffs.0.31
  - PKG=xapi-storage-script.xapi-project#master
  - PKG=xapi-storage.xapi-project#master
  - PKG=xapi-tapctl.xapi-project#master
  - PKG=xapi-test-utils.xapi-project#master
  - PKG=xapi.xapi-project#master
  - PKG=xapi-xenops.xapi-project#master
  - PKG=xapi-xenopsd.xapi-project#master
  - PKG=xen-api-client.xapi-project#master
  - PKG=xenctrl.xapi-project#master
